# Generated by Django 4.1 on 2022-10-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recepes',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
    ]
